name: smashlibs
description: Libs and utilities used by the SMASH digital field mapping project.

# Copyright (c) 2019-2020. www.hydrologis.com. All rights reserved.
# Use of this source code is governed by a GPL3 license that can be
# found in the LICENSE file.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  ##################
  # OWN
  #################

  #BSD
  dart_jts: ^0.2.1+1
    # path: ../dart_jts/
  #    git:
  #      url: https://github.com/moovida/dart_jts.git

  dart_hydrologis_utils: ^0.6.1
    # path: ../dart_hydrologis_utils/

  dart_hydrologis_db: ^1.0.0
    # path: ../dart_hydrologis_db/
  # git:
  #  url: https://github.com/moovida/dart_hydrologis_db.git

  ####################
  # OTHERS
  ####################
  # BSD
  # charset_converter: ^1.0.3
  # MIT
  material_design_icons_flutter: ^5.0.6996
  
  # MIT
  share_extend: ^2.0.0
  # BSD
  path_provider: ^2.0.11
  
  # MIT (possible substitute external_path)
  path_provider_ex: #^1.0.1
    git:
      url: https://github.com/atrope/flutter_path_provider_ex.git
      ref: feature/nullsafemigration
  # MIT
  proj4dart: ^2.1.0
  # MIT
  dio: ^4.0.6
  # MIT
  permission_handler: ^10.0.0
    # git: 
    #   url: https://github.com/Baseflow/flutter-permission-handler.git
    #   path: permission_handler

  # BSD
  device_info_plus: ^8.0.0
  # MIT
  after_layout: ^1.2.0

  # BSD
  url_launcher: ^6.1.5

  # MIT
  flutter_tags_x: ^1.1.0

  # MIT
  flutter_material_pickers: #^3.1.4+1
    git:
      url: https://github.com/moovida/flutter_material_pickers.git
      ref: 1b9f72c

  # BSD
  shared_preferences: ^2.0.15
  # MIT
  flutter_screen_wake: ^1.0.2
  # ON ANDROID NEEDS:
  # <uses-permission android:name="android.permission.WAKE_LOCK" />

  #BSD
  image_picker: ^0.8.5+3
  # ON IOS NEEDS:
  #  <key>NSPhotoLibraryUsageDescription</key>
  #  <string>The app needs to access the photo library to attach media to the survey.</string>
  #  <key>NSCameraUsageDescription</key>
  #  <string>The app needs to use the camera to take picture notes during the field mapping activity.</string>
  #  <key>NSMicrophoneUsageDescription</key>
  #  <string>The app needs to use the camera to take vocal notes during the field mapping activity.</string>

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
